# Generated by Django 4.1.2 on 2022-10-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='id',
            new_name='channel_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='channel',
            new_name='channel_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='id',
            new_name='video_id',
        ),
    ]
