# Generated by Django 4.1.2 on 2022-10-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_rename_id_channel_channel_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='channel_id',
            new_name='channel',
        ),
    ]
